name: Storm CMS Media
description: Storm CMS Media
recipes:
  - core/recipes/document_media_type
  - core/recipes/remote_video_media_type
  - core/recipes/local_video_media_type
  - core/recipes/standard_responsive_images
install:
  - media
  - media_library
  - filefield_paths
  - focal_point
  - media_entity_download
  - webp
  - responsive_image
  - lazy
  - taxonomy
  - media_file_delete
  - select2
config:
  actions:
    user.role.anonymous:
      grantPermissions:
        - 'download media'
        - 'view media'
    user.role.authenticated:
      grantPermissions:
        - 'download media'
        - 'view media'
    user.role.content_editor:
      grantPermissions:
        - 'download media'
        - 'view media'
